const frasesBonitas = [
    "Eres mi todo",
    "Te adoro",
    "Eres la luz de mi vida",
    "Mi razón de ser",
    "Juntos por siempre",
    "Eres mi musa",
    "Te extraño",
    "Eres especial",
    "Risa contagiosa",
    "Nuestro amor es eterno",
    "Eres mi vida",
    "Somos inseparables",
    "Nuestro futuro juntos",
    "Nuestro amor es infinito",
    "Nuestros caminos están entrelazados",
    "Tu sonrisa es mi melodía",
    "Eres mi compañera de vida",
    "Nuestro amor es sincero",
    "Estamos destinados a estar juntos",
    "Eres mi alma gemela",
    "Juntos somos invencibles",
    "Eres mi refugio",
    "Todo lo hago por ti",
    "Eres mi ilusión diaria",
    "Eres mi tesoro más preciado",
    "Te necesito a mi lado",
    "Siempre estaremos juntos",
    "Nuestro amor es verdadero",
    "Eres mi paz",
    "Nuestro rincón es especial",
    "Contigo en las buenas y malas",
    "Eres mi hogar",
    "Lo mejor de mi vida eres tú",
    "Eres mi alegría constante",
    "Eres perfecta para mí",
    "Siempre estarás en mi corazón",
    "Eres mi inspiración diaria",
    "Eres mi motivo para sonreír",
    "Eres mi sol en días grises",
    "Te amo más cada día",
    "Nuestro destino es juntos",
    "Eres mi sueño hecho realidad",
    "Eres mi felicidad",
    "Te elijo a ti cada día",
    "Eres mi fortaleza",
    "Mi corazón late por ti",
    "Vivimos un cuento de hadas",
    "Nuestro amor es eterno",
    "Eres mi mundo",
    "Juntos somos mejores",
    "Eres mi mejor amiga y amor",
    "Eres mi otra mitad",
    "Eres mi sonrisa diaria",
    "Nuestro siempre es ahora",
    "Te quiero más que a nada",
    "Eres mi paz y mi tormenta",
    "Te admiro profundamente",
    "Nuestro amor crece cada día",
    "Eres mi sueño cumplido",
    "Siempre estás en mis pensamientos",
    "Eres mi mejor regalo",
    "Eres mi gran amor",
    "Juntos hasta el fin del mundo",
    "Te amo con locura",
    "Mi destino eres tú",
    "Eres mi razón para vivir",
    "Eres mi mejor decisión",
    "Nuestro amor es mágico",
    "Eres mi complemento perfecto",
    "Eres mi todo en este mundo",
    "Eres la razón de mi sonrisa",
    "Cada día te amo más",
    "Nuestro amor es un viaje hermoso",
    "Eres mi refugio seguro",
    "Te amo más allá de las palabras",
    "Eres mi historia de amor favorita",
    "Cada momento contigo es especial",
    "Eres mi mejor aventura",
    "Eres el amor de mi vida",
    "Siempre estaré a tu lado",
    "Eres mi sol y mi luna",
    "Eres mi mayor bendición",
    "Nuestro amor es eterno",
    "Eres mi felicidad infinita",
    "Te amo con todo mi ser",
    "Eres mi todo y más",
    "Eres mi sueño hecho realidad",
    "Eres mi amor eterno",
    "Eres mi razón de ser feliz",
    "Eres mi inspiración",
    "Eres mi compañera de vida",
    "Eres mi alegría diaria",
    "Te amo más que a nada",
    "Eres mi paz y mi tormenta",
    "Nuestro amor es invencible",
    "Eres mi mundo entero",
    "Eres mi razón para luchar",
    "Eres mi destino",
    "Te amo más que nunca",
    "Eres mi mejor historia de amor",
    "Eres mi vida entera"
  ];
  
let running = false
  
function getRandomInt(max) {
  return Math.floor(Math.random() * max);
}
function setText(){
    document.getElementById("phrases").innerHTML = frasesBonitas[getRandomInt(frasesBonitas.length)]
}
function playMusic(){
    var music = document.getElementById("music");
    music.play()
}
function stopMusic(){
    var music = document.getElementById("music");
    music.pause()
}

